app:
  runType: Both
  outputPath: /home/sbaldin
  sendEmail: myEmail@gmail.com
employee:
  name: Ivan Ivanov
  invoiceDate: Janurary 1, 1970
  contractDate: Janurary 1, 1970
  serviceProvider: Platform Development
  vacationDaysInMonth: 0
  vacationDaysInYear: 0
  monthRate: 0
  additionalExpenses: 0
bankingDetails:
  name: AO «ALFA-BANK»
  accountNumber: 00000 000 0000 0000 0000
  country: Russia
  bankAddress: 27 Kalanchevskaya str., Moscow, 107078, tel +7 495 755-58-58, SWIFT ALFARUMM
  beneficiaryName: IP Ivanov Ivan Ivanovich
  beneficiaryAdress: PR. LENINA, D. 1, KV. 1, KEMEROVO, RUSSIA, 650000





